language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

sudo: false

addons:
  apt:
    packages:
      - python-numpy

env:
    - AUTOCLONE="y"

install:
  - pip install nose-cov python-coveralls sphinx
  - pip install -r requirements.txt

script:
  - nosetests

after_success:
  - openssl aes-256-cbc -K $encrypted_fdd6915d24a6_key -iv $encrypted_fdd6915d24a6_iv -in .pypirc.enc -out ~/.pypirc -d
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a $TRAVIS_PYTHON_VERSION == "2.7" ]; then
      make publish;
    fi

notifications:
 slack:
 email: false
